import { logger } from './logger'
import type { Bookmark } from '@/types/bookmark'

/**
 * Load demo tweets from pre-generated static JSON file
 * The JSON file is generated by running: npm run fetch-demo-tweets
 */
export async function fetchLiveTweets(): Promise<Bookmark[]> {
  try {
    logger.info('Loading demo tweets from static JSON...')

    const response = await fetch('/demo-tweets.json')

    if (!response.ok) {
      logger.warn(`Failed to load demo-tweets.json: ${response.status}`)
      return []
    }

    const data = await response.json()

    if (!data.bookmarks || !Array.isArray(data.bookmarks)) {
      logger.warn('Invalid demo-tweets.json format')
      return []
    }

    logger.info(
      `✓ Loaded ${data.bookmarks.length} demo tweets (generated: ${data.generated_at})`
    )

    return data.bookmarks
  } catch (error) {
    logger.warn('Failed to load demo tweets from JSON:', error)
    return []
  }
}

/**
 * Alias for backwards compatibility
 */
export async function fetchPopularTechTweets(): Promise<Bookmark[]> {
  return fetchLiveTweets()
}
